/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MySavesRouteImport } from './routes/my-saves'
import { Route as MyPlansRouteImport } from './routes/my-plans'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddBusinessRouteImport } from './routes/add-business'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlacePlaceIdRouteImport } from './routes/place/$placeId'
import { Route as MoodTouristDayOutRouteImport } from './routes/mood/tourist-day-out'
import { Route as MoodQuietWorkRouteImport } from './routes/mood/quiet-work'
import { Route as MoodFamilyDinnerRouteImport } from './routes/mood/family-dinner'
import { Route as MoodDateRouteImport } from './routes/mood/date'
import { Route as MoodCoffeeGuffRouteImport } from './routes/mood/coffee-guff'
import { Route as MoodBudgetHangoutRouteImport } from './routes/mood/budget-hangout'
import { Route as MoodMoodIdRouteImport } from './routes/mood/$moodId'
import { Route as BusinessAccountRouteImport } from './routes/business/account'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as BusinessEditIdRouteImport } from './routes/business/edit/$id'

const MySavesRoute = MySavesRouteImport.update({
  id: '/my-saves',
  path: '/my-saves',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPlansRoute = MyPlansRouteImport.update({
  id: '/my-plans',
  path: '/my-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBusinessRoute = AddBusinessRouteImport.update({
  id: '/add-business',
  path: '/add-business',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacePlaceIdRoute = PlacePlaceIdRouteImport.update({
  id: '/place/$placeId',
  path: '/place/$placeId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodTouristDayOutRoute = MoodTouristDayOutRouteImport.update({
  id: '/mood/tourist-day-out',
  path: '/mood/tourist-day-out',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodQuietWorkRoute = MoodQuietWorkRouteImport.update({
  id: '/mood/quiet-work',
  path: '/mood/quiet-work',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodFamilyDinnerRoute = MoodFamilyDinnerRouteImport.update({
  id: '/mood/family-dinner',
  path: '/mood/family-dinner',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodDateRoute = MoodDateRouteImport.update({
  id: '/mood/date',
  path: '/mood/date',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodCoffeeGuffRoute = MoodCoffeeGuffRouteImport.update({
  id: '/mood/coffee-guff',
  path: '/mood/coffee-guff',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodBudgetHangoutRoute = MoodBudgetHangoutRouteImport.update({
  id: '/mood/budget-hangout',
  path: '/mood/budget-hangout',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodMoodIdRoute = MoodMoodIdRouteImport.update({
  id: '/mood/$moodId',
  path: '/mood/$moodId',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAccountRoute = BusinessAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => BusinessRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const BusinessEditIdRoute = BusinessEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => BusinessRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-business': typeof AddBusinessRoute
  '/admin': typeof AdminRouteWithChildren
  '/business': typeof BusinessRouteWithChildren
  '/my-plans': typeof MyPlansRoute
  '/my-saves': typeof MySavesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/business/account': typeof BusinessAccountRoute
  '/mood/$moodId': typeof MoodMoodIdRoute
  '/mood/budget-hangout': typeof MoodBudgetHangoutRoute
  '/mood/coffee-guff': typeof MoodCoffeeGuffRoute
  '/mood/date': typeof MoodDateRoute
  '/mood/family-dinner': typeof MoodFamilyDinnerRoute
  '/mood/quiet-work': typeof MoodQuietWorkRoute
  '/mood/tourist-day-out': typeof MoodTouristDayOutRoute
  '/place/$placeId': typeof PlacePlaceIdRoute
  '/business/edit/$id': typeof BusinessEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-business': typeof AddBusinessRoute
  '/admin': typeof AdminRouteWithChildren
  '/business': typeof BusinessRouteWithChildren
  '/my-plans': typeof MyPlansRoute
  '/my-saves': typeof MySavesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/business/account': typeof BusinessAccountRoute
  '/mood/$moodId': typeof MoodMoodIdRoute
  '/mood/budget-hangout': typeof MoodBudgetHangoutRoute
  '/mood/coffee-guff': typeof MoodCoffeeGuffRoute
  '/mood/date': typeof MoodDateRoute
  '/mood/family-dinner': typeof MoodFamilyDinnerRoute
  '/mood/quiet-work': typeof MoodQuietWorkRoute
  '/mood/tourist-day-out': typeof MoodTouristDayOutRoute
  '/place/$placeId': typeof PlacePlaceIdRoute
  '/business/edit/$id': typeof BusinessEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-business': typeof AddBusinessRoute
  '/admin': typeof AdminRouteWithChildren
  '/business': typeof BusinessRouteWithChildren
  '/my-plans': typeof MyPlansRoute
  '/my-saves': typeof MySavesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/business/account': typeof BusinessAccountRoute
  '/mood/$moodId': typeof MoodMoodIdRoute
  '/mood/budget-hangout': typeof MoodBudgetHangoutRoute
  '/mood/coffee-guff': typeof MoodCoffeeGuffRoute
  '/mood/date': typeof MoodDateRoute
  '/mood/family-dinner': typeof MoodFamilyDinnerRoute
  '/mood/quiet-work': typeof MoodQuietWorkRoute
  '/mood/tourist-day-out': typeof MoodTouristDayOutRoute
  '/place/$placeId': typeof PlacePlaceIdRoute
  '/business/edit/$id': typeof BusinessEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-business'
    | '/admin'
    | '/business'
    | '/my-plans'
    | '/my-saves'
    | '/admin/submissions'
    | '/admin/users'
    | '/business/account'
    | '/mood/$moodId'
    | '/mood/budget-hangout'
    | '/mood/coffee-guff'
    | '/mood/date'
    | '/mood/family-dinner'
    | '/mood/quiet-work'
    | '/mood/tourist-day-out'
    | '/place/$placeId'
    | '/business/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-business'
    | '/admin'
    | '/business'
    | '/my-plans'
    | '/my-saves'
    | '/admin/submissions'
    | '/admin/users'
    | '/business/account'
    | '/mood/$moodId'
    | '/mood/budget-hangout'
    | '/mood/coffee-guff'
    | '/mood/date'
    | '/mood/family-dinner'
    | '/mood/quiet-work'
    | '/mood/tourist-day-out'
    | '/place/$placeId'
    | '/business/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/add-business'
    | '/admin'
    | '/business'
    | '/my-plans'
    | '/my-saves'
    | '/admin/submissions'
    | '/admin/users'
    | '/business/account'
    | '/mood/$moodId'
    | '/mood/budget-hangout'
    | '/mood/coffee-guff'
    | '/mood/date'
    | '/mood/family-dinner'
    | '/mood/quiet-work'
    | '/mood/tourist-day-out'
    | '/place/$placeId'
    | '/business/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddBusinessRoute: typeof AddBusinessRoute
  AdminRoute: typeof AdminRouteWithChildren
  BusinessRoute: typeof BusinessRouteWithChildren
  MyPlansRoute: typeof MyPlansRoute
  MySavesRoute: typeof MySavesRoute
  MoodMoodIdRoute: typeof MoodMoodIdRoute
  MoodBudgetHangoutRoute: typeof MoodBudgetHangoutRoute
  MoodCoffeeGuffRoute: typeof MoodCoffeeGuffRoute
  MoodDateRoute: typeof MoodDateRoute
  MoodFamilyDinnerRoute: typeof MoodFamilyDinnerRoute
  MoodQuietWorkRoute: typeof MoodQuietWorkRoute
  MoodTouristDayOutRoute: typeof MoodTouristDayOutRoute
  PlacePlaceIdRoute: typeof PlacePlaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-saves': {
      id: '/my-saves'
      path: '/my-saves'
      fullPath: '/my-saves'
      preLoaderRoute: typeof MySavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-plans': {
      id: '/my-plans'
      path: '/my-plans'
      fullPath: '/my-plans'
      preLoaderRoute: typeof MyPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-business': {
      id: '/add-business'
      path: '/add-business'
      fullPath: '/add-business'
      preLoaderRoute: typeof AddBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$placeId': {
      id: '/place/$placeId'
      path: '/place/$placeId'
      fullPath: '/place/$placeId'
      preLoaderRoute: typeof PlacePlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/tourist-day-out': {
      id: '/mood/tourist-day-out'
      path: '/mood/tourist-day-out'
      fullPath: '/mood/tourist-day-out'
      preLoaderRoute: typeof MoodTouristDayOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/quiet-work': {
      id: '/mood/quiet-work'
      path: '/mood/quiet-work'
      fullPath: '/mood/quiet-work'
      preLoaderRoute: typeof MoodQuietWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/family-dinner': {
      id: '/mood/family-dinner'
      path: '/mood/family-dinner'
      fullPath: '/mood/family-dinner'
      preLoaderRoute: typeof MoodFamilyDinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/date': {
      id: '/mood/date'
      path: '/mood/date'
      fullPath: '/mood/date'
      preLoaderRoute: typeof MoodDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/coffee-guff': {
      id: '/mood/coffee-guff'
      path: '/mood/coffee-guff'
      fullPath: '/mood/coffee-guff'
      preLoaderRoute: typeof MoodCoffeeGuffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/budget-hangout': {
      id: '/mood/budget-hangout'
      path: '/mood/budget-hangout'
      fullPath: '/mood/budget-hangout'
      preLoaderRoute: typeof MoodBudgetHangoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/$moodId': {
      id: '/mood/$moodId'
      path: '/mood/$moodId'
      fullPath: '/mood/$moodId'
      preLoaderRoute: typeof MoodMoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/account': {
      id: '/business/account'
      path: '/account'
      fullPath: '/business/account'
      preLoaderRoute: typeof BusinessAccountRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/business/edit/$id': {
      id: '/business/edit/$id'
      path: '/edit/$id'
      fullPath: '/business/edit/$id'
      preLoaderRoute: typeof BusinessEditIdRouteImport
      parentRoute: typeof BusinessRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BusinessRouteChildren {
  BusinessAccountRoute: typeof BusinessAccountRoute
  BusinessEditIdRoute: typeof BusinessEditIdRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessAccountRoute: BusinessAccountRoute,
  BusinessEditIdRoute: BusinessEditIdRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddBusinessRoute: AddBusinessRoute,
  AdminRoute: AdminRouteWithChildren,
  BusinessRoute: BusinessRouteWithChildren,
  MyPlansRoute: MyPlansRoute,
  MySavesRoute: MySavesRoute,
  MoodMoodIdRoute: MoodMoodIdRoute,
  MoodBudgetHangoutRoute: MoodBudgetHangoutRoute,
  MoodCoffeeGuffRoute: MoodCoffeeGuffRoute,
  MoodDateRoute: MoodDateRoute,
  MoodFamilyDinnerRoute: MoodFamilyDinnerRoute,
  MoodQuietWorkRoute: MoodQuietWorkRoute,
  MoodTouristDayOutRoute: MoodTouristDayOutRoute,
  PlacePlaceIdRoute: PlacePlaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
