/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AddBusinessRouteImport } from './routes/add-business'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoodTouristDayOutRouteImport } from './routes/mood/tourist-day-out'
import { Route as MoodQuietWorkRouteImport } from './routes/mood/quiet-work'
import { Route as MoodFamilyDinnerRouteImport } from './routes/mood/family-dinner'
import { Route as MoodDateRouteImport } from './routes/mood/date'
import { Route as MoodCoffeeGuffRouteImport } from './routes/mood/coffee-guff'
import { Route as MoodBudgetHangoutRouteImport } from './routes/mood/budget-hangout'
import { Route as MoodMoodIdRouteImport } from './routes/mood/$moodId'

const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBusinessRoute = AddBusinessRouteImport.update({
  id: '/add-business',
  path: '/add-business',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodTouristDayOutRoute = MoodTouristDayOutRouteImport.update({
  id: '/mood/tourist-day-out',
  path: '/mood/tourist-day-out',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodQuietWorkRoute = MoodQuietWorkRouteImport.update({
  id: '/mood/quiet-work',
  path: '/mood/quiet-work',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodFamilyDinnerRoute = MoodFamilyDinnerRouteImport.update({
  id: '/mood/family-dinner',
  path: '/mood/family-dinner',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodDateRoute = MoodDateRouteImport.update({
  id: '/mood/date',
  path: '/mood/date',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodCoffeeGuffRoute = MoodCoffeeGuffRouteImport.update({
  id: '/mood/coffee-guff',
  path: '/mood/coffee-guff',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodBudgetHangoutRoute = MoodBudgetHangoutRouteImport.update({
  id: '/mood/budget-hangout',
  path: '/mood/budget-hangout',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodMoodIdRoute = MoodMoodIdRouteImport.update({
  id: '/mood/$moodId',
  path: '/mood/$moodId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-business': typeof AddBusinessRoute
  '/business': typeof BusinessRoute
  '/mood/$moodId': typeof MoodMoodIdRoute
  '/mood/budget-hangout': typeof MoodBudgetHangoutRoute
  '/mood/coffee-guff': typeof MoodCoffeeGuffRoute
  '/mood/date': typeof MoodDateRoute
  '/mood/family-dinner': typeof MoodFamilyDinnerRoute
  '/mood/quiet-work': typeof MoodQuietWorkRoute
  '/mood/tourist-day-out': typeof MoodTouristDayOutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-business': typeof AddBusinessRoute
  '/business': typeof BusinessRoute
  '/mood/$moodId': typeof MoodMoodIdRoute
  '/mood/budget-hangout': typeof MoodBudgetHangoutRoute
  '/mood/coffee-guff': typeof MoodCoffeeGuffRoute
  '/mood/date': typeof MoodDateRoute
  '/mood/family-dinner': typeof MoodFamilyDinnerRoute
  '/mood/quiet-work': typeof MoodQuietWorkRoute
  '/mood/tourist-day-out': typeof MoodTouristDayOutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-business': typeof AddBusinessRoute
  '/business': typeof BusinessRoute
  '/mood/$moodId': typeof MoodMoodIdRoute
  '/mood/budget-hangout': typeof MoodBudgetHangoutRoute
  '/mood/coffee-guff': typeof MoodCoffeeGuffRoute
  '/mood/date': typeof MoodDateRoute
  '/mood/family-dinner': typeof MoodFamilyDinnerRoute
  '/mood/quiet-work': typeof MoodQuietWorkRoute
  '/mood/tourist-day-out': typeof MoodTouristDayOutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-business'
    | '/business'
    | '/mood/$moodId'
    | '/mood/budget-hangout'
    | '/mood/coffee-guff'
    | '/mood/date'
    | '/mood/family-dinner'
    | '/mood/quiet-work'
    | '/mood/tourist-day-out'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-business'
    | '/business'
    | '/mood/$moodId'
    | '/mood/budget-hangout'
    | '/mood/coffee-guff'
    | '/mood/date'
    | '/mood/family-dinner'
    | '/mood/quiet-work'
    | '/mood/tourist-day-out'
  id:
    | '__root__'
    | '/'
    | '/add-business'
    | '/business'
    | '/mood/$moodId'
    | '/mood/budget-hangout'
    | '/mood/coffee-guff'
    | '/mood/date'
    | '/mood/family-dinner'
    | '/mood/quiet-work'
    | '/mood/tourist-day-out'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddBusinessRoute: typeof AddBusinessRoute
  BusinessRoute: typeof BusinessRoute
  MoodMoodIdRoute: typeof MoodMoodIdRoute
  MoodBudgetHangoutRoute: typeof MoodBudgetHangoutRoute
  MoodCoffeeGuffRoute: typeof MoodCoffeeGuffRoute
  MoodDateRoute: typeof MoodDateRoute
  MoodFamilyDinnerRoute: typeof MoodFamilyDinnerRoute
  MoodQuietWorkRoute: typeof MoodQuietWorkRoute
  MoodTouristDayOutRoute: typeof MoodTouristDayOutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-business': {
      id: '/add-business'
      path: '/add-business'
      fullPath: '/add-business'
      preLoaderRoute: typeof AddBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/tourist-day-out': {
      id: '/mood/tourist-day-out'
      path: '/mood/tourist-day-out'
      fullPath: '/mood/tourist-day-out'
      preLoaderRoute: typeof MoodTouristDayOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/quiet-work': {
      id: '/mood/quiet-work'
      path: '/mood/quiet-work'
      fullPath: '/mood/quiet-work'
      preLoaderRoute: typeof MoodQuietWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/family-dinner': {
      id: '/mood/family-dinner'
      path: '/mood/family-dinner'
      fullPath: '/mood/family-dinner'
      preLoaderRoute: typeof MoodFamilyDinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/date': {
      id: '/mood/date'
      path: '/mood/date'
      fullPath: '/mood/date'
      preLoaderRoute: typeof MoodDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/coffee-guff': {
      id: '/mood/coffee-guff'
      path: '/mood/coffee-guff'
      fullPath: '/mood/coffee-guff'
      preLoaderRoute: typeof MoodCoffeeGuffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/budget-hangout': {
      id: '/mood/budget-hangout'
      path: '/mood/budget-hangout'
      fullPath: '/mood/budget-hangout'
      preLoaderRoute: typeof MoodBudgetHangoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood/$moodId': {
      id: '/mood/$moodId'
      path: '/mood/$moodId'
      fullPath: '/mood/$moodId'
      preLoaderRoute: typeof MoodMoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddBusinessRoute: AddBusinessRoute,
  BusinessRoute: BusinessRoute,
  MoodMoodIdRoute: MoodMoodIdRoute,
  MoodBudgetHangoutRoute: MoodBudgetHangoutRoute,
  MoodCoffeeGuffRoute: MoodCoffeeGuffRoute,
  MoodDateRoute: MoodDateRoute,
  MoodFamilyDinnerRoute: MoodFamilyDinnerRoute,
  MoodQuietWorkRoute: MoodQuietWorkRoute,
  MoodTouristDayOutRoute: MoodTouristDayOutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
